### ISSUE TITLE
No smooth movement

### ISSUE THREAD

**Issue by jv-barsuk** [PhotoFilmStrip/PFS#10]
When I use panoramic images and move along them the video is not very smooth and always stutters. What could be the reason for it and how could I fix it? I'm using OGR/FULL-HD/PAL.

**Comment by jensgoe** [comment]
I have added more options for frame rate settings. So higher frame rate should result in smoother movement. See  #13. Closed via commit 5526b2c771859d0b94da4e206c778b00b17b38b5.
