### ISSUE TITLE
4.0.0-1 : Match video to audio

### ISSUE THREAD

**Issue by Lehmeiers** [PhotoFilmStrip/PFS#103]
Hello!
I would like to embed multiple music tracks and then adjust the video to the audio length. But Photofilmstrip tells me that he can only for one title. 
Therefore, I would like to suggest that this is changed and the number of tracks is not limited, so that an arbitrarily long music selection can be adapted to a video.

Otherwise I have to save several titles, for example with Audacity, as one long title and then let it adapt - but this is unnecessarily cumbersome.

Sincerely R.Lehmeier

Translated with www.DeepL.com/Translator (free version)

**Comment by jensgoe** [comment]
Hi,
thanks for all the suggestions (other issues too 👍).

![image](https://user-images.githubusercontent.com/6022600/202037318-2cc018e6-1136-4c0e-ac1f-c12f73783051.png)

With this option checked, the slideshow would have the length of all audio files together. The tool button next to it (with little clock) is used for #34. This feature is currently supported with one music track.

Jens

**Comment by Lehmeiers** [comment]
Thank you, it works
