### ISSUE TITLE
Can't run PhotoFilmStrip

### ISSUE THREAD

**Issue by LukeLR** [PhotoFilmStrip/PFS#11]
First things first: Thanks for this great piece of software! It's mentioned on [the Ubuntuusers.de Wiki for creating diashows ("Diashows erstellen")](https://wiki.ubuntuusers.de/Diashows_erstellen), and I was glad to find some software for that task that's not just ancient. So thanks for your hard work!

Unfortunately, I can't run PhotoFilmStrip. When using `python setup.py build`, the script returns immediately only with output `Cannot update image resources! Using images.py from source`. `sudo python setup.py install` gives me a huge bunch of syntax errors (see the complete error output in [this gist](https://gist.github.com/LukeLR/d7c0c6f0416458393e975a73a9790423)).

So how am I supposed to run the software? I couldn't find any instructions on that. Your [website](http://www.photofilmstrip.org/4-0-Download.html) says to run `photofilmstrip-gui.py` from the `src`-directory, but there is no src directory here, right? I'd be glad if you could give some information 😄 

Thanks in advance,
Lukas

**Comment by jensgoe** [comment]
It seems you are trying to run PhotoFilmStrip with python3. Your should install python2.7 or if it is already installed try "python2 setup.py build".
Thanks for the hint with the src-folder. Seems that my website is outdated. The src-folder is now named "photofilmstrip".
You can run it by:
export PYTHONPATH=`pwd`
python photofilmstrip/GUI.py
