### ISSUE TITLE
Adjust picture durations to audio file

### ISSUE THREAD

**Issue by jensgoe** [PhotoFilmStrip/PFS#34]
1. open a configuration dialog to see the numbers of pictures in a list
2. press a play button to play the audio file configured in the project properties
3. listen to the music and press space or a button when the slideshow should switch to the next picture
4. in the list the user can see for each a picture the duration according to the current playing time
5. after confirming the dialog all the durations are applied to the transition length for every picture

the music in the rendered slideshow matches to the picture transitions

**Comment by jensgoe** [comment]
starting with commit 8668272e75bcf11beec9fec8984631556f353677

**Comment by achimwagenknecht** [comment]
Thank you very much for beginning this! Looking forward to the feature. :-)

**Comment by jensgoe** [comment]
closed via #35
