### ISSUE TITLE
[Feature request] Video clips as input

### ISSUE THREAD

**Issue by sargue** [PhotoFilmStrip/PFS#40]
This is a feature request.

Having moved from the old MemoriesOnTV to this software I miss this feature. The ability to add video clips inside the timeline along with still images.

When rendering the resulting video a video clip is simply added along, no effects, just attached. The background music could be silenced to simplify things.

**Comment by jensgoe** [comment]
Its been a while. This is a indeed a feature i miss myself and i am already working on it. The first version will probably realize this as a separate step after creating the slideshow. So first do all the image stuff and after that combine all videos. I keep you updated ;-)

**Comment by sargue** [comment]
Hi. Thanks for your feedback. As I needed that feature I ended researching about an alternative and ended forking and updating another project which uses `ffmpeg`. It's not fast and requires a quite powerful machine but solves my problem for the moment.

The project can be found here: https://github.com/sargue/kburns

**Comment by jensgoe** [comment]
This feature will be realized by #45
