### ISSUE TITLE
Builds no longer after #50 merge 

### ISSUE THREAD

**Issue by pepa65** [PhotoFilmStrip/PFS#51]
At 4315d07b05123960e57d67b3051a380e9c588f6c I can no longer build. Even if I do `python setup.py clean` and then `python setup.py build` it comes back with `Cannot update image resources! Using images.py from source`.

Hmm I need some wx libraries. With `python-wxtools` it seems to build with python 2.7 (but not install) but not with python3... Any suggestions??

OK, found it. On Ubuntu 18.04 just install `python3-wxgtk4.0` and it works again. Well, the build and install don't error out. But it doesn't run. Something is not working...

Now I installed `gir1.2-ges-1.0` and the PhotoFilmStrip window comes up..! (With a number of warnings on the terminal...)

**Comment by jensgoe** [comment]
I am confused. Do you still have a problem?
The message `Cannot update image resources! Using images.py from source.` should only be a warning. So python3-wxgtk4.0 should not be needed only for building.
python 2.7 is not supported anymore.

**Comment by pepa65** [comment]
Still unusable after `python3 setup.py build; sudo python3 setup.py install`.
Now only the warning `Cannot update image resources! Using images.py from source` comes up on both build and install.
When running `photofilmstrip` the output is:
```
/usr/lib/python3/dist-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3/dist-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3/dist-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/local/bin/photofilmstrip", line 8, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/photofilmstrip/GUI.py", line 45, in main
    guiApp.Start()
  File "/usr/local/lib/python3.6/dist-packages/photofilmstrip/AppMixin.py", line 55, in Start
    return self._OnStart()
  File "/usr/local/lib/python3.6/dist-packages/photofilmstrip/GUI.py", line 21, in _OnStart
    import wx
ModuleNotFoundError: No module named 'wx'
```
I don't know what else to install...

**Comment by jensgoe** [comment]
No module named 'wx' means wxPython4 is not found. Can you run "import wx" within a python console?

**Comment by jensgoe** [comment]
One more thing. Can you check wich python interpreter is called if you run the executable "photofilmstrip". You can check with:
`cat /usr/bin/photofilmstrip`
Check the first line if it shows `#!/usr/bin/python3`. Is it the right python interpreter?

**Comment by pepa65** [comment]
Had the same thing: install `python3-wxgtk4.0` solved it for me.

**Comment by jensgoe** [comment]
I also get the warnings. But i have no clue how to fix them.

**Comment by pepa65** [comment]
It seems Gtk often gives warnings...
