### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by CocoCocoAlx** [PhotoFilmStrip/PFS#53]
Hello, if no one can do it, I offer myself to translate the interface of the program into Spanish. Can I? Thank you very much.

**Comment by CocoCocoAlx** [comment]
Here is my translation. I've made this with PoEdit, I'm very newbie in those things. Sorry. Many thanks for your work! Greetings!

[PhotoFilmStrip_es.zip](https://github.com/PhotoFilmStrip/PFS/files/3660018/PhotoFilmStrip_es.zip)

**Comment by CocoCocoAlx** [comment]
Here is. I've made with PoEdit, I'm a newbie in this things... sorry if I was made a mistake. That's all. Many thanks for your work!

[PhotoFilmStrip_spa.zip](https://github.com/PhotoFilmStrip/PFS/files/3660098/PhotoFilmStrip_spa.zip)

**Comment by jensgoe** [comment]
Sorry for the delay. Thanks a lot. It is perfect using PoEdit. I am going to apply the changes very soon
