### ISSUE TITLE
Option to mux in the subtitles

### ISSUE THREAD

**Issue by pepa65** [PhotoFilmStrip/PFS#7]
It would be great to have an option to mux in the subtitle, so it can be played on dumb devices.

**Comment by jensgoe** [comment]
Thats already possible. In the render dialog you have a little tool button for render properties. Next to the format choice. In the list set the value for RenderSubtitle to "true" or 1.

**Comment by pepa65** [comment]
Never saw that..! For the less adventurous, you could consider calling it "hardcode" or "burn in" to make it absolutely clear, because most people want the subtitles to be rendered in some way.

**Comment by pepa65** [comment]
And thank you for this great app, have been using it for many years!
