### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by df1paw** [PhotoFilmStrip/PFS#74]
Please add support for entering an own aspect ratio - or at least portrait mode resolutions for mobile phone optimized videos.

Thanks.

**Comment by jensgoe** [comment]
Thanks for the reminder. I give it a try.

**Comment by pacovila** [comment]
Sweet!
Thank you

El 23 de diciembre de 2022 14:57:27 CET, jensgoe ***@***.***> escribió:
>Closed #74 as completed via 47089168911f772e8562ff593f60557c3edf8e99.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/PhotoFilmStrip/PFS/issues/74#event-8103565818
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
