### ISSUE TITLE
photofilmstrip not working - ValueError: Namespace GES not available

### ISSUE THREAD

**Issue by Mesqualito** [PhotoFilmStrip/PFS#78]
On ubuntu Focal Fossa (Ubuntu 20.04.1 LTS) I tried to run the program:

`$ python3 --version`
Python 3.8.2

`$ python3 setup.py build`
Embedded [path_to_source]/res/icons/photofilmstrip_16.png using "ICON_16" into photofilmstrip/res/images.py
[...]
Embedded [path_to_source]/res/icons/dia_s.png using "DIA_S" into photofilmstrip/res/images.py

`$ sudo python3 setup.py install`
Embedded [path_to_source]/res/icons/photofilmstrip_16.png using "ICON_16" into photofilmstrip/res/images.py
[...]
Embedded [path_to_source]/res/icons/dia_s.png using "DIA_S" into photofilmstrip/res/images.py

`$ python3 build/scripts-3.8/photofilmstrip`
Traceback (most recent call last):
  File "build/scripts-3.8/photofilmstrip", line 8, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/photofilmstrip/GUI.py", line 45, in main
    guiApp.Start()
  File "/usr/local/lib/python3.8/dist-packages/photofilmstrip/AppMixin.py", line 47, in Start
    self.InitGLib()
  File "/usr/local/lib/python3.8/dist-packages/photofilmstrip/AppMixin.py", line 37, in InitGLib
    gi.require_version('GES', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GES not available

`$ sudo apt list --installed | egrep -i 'python3-gst-1.0*|gir1.2-gstreamer-1.0*|gir1.2-gst-plugins-base-1.0*|gstreamer1.0-plugins-good*|gstreamer1.0-plugins-ugly*|gstreamer1.0-tools*'`
gir1.2-gst-plugins-base-1.0/focal,now 1.16.2-4 amd64  [installiert]
gir1.2-gstreamer-1.0/focal,now 1.16.2-2 amd64  [installiert]
gstreamer1.0-plugins-good/focal,now 1.16.2-1ubuntu2 amd64  [installiert]
gstreamer1.0-plugins-ugly/focal,now 1.16.2-2build1 amd64  [installiert]
gstreamer1.0-tools/focal,now 1.16.2-2 amd64  [installiert]
python3-gst-1.0/focal,now 1.16.2-2 amd64  [installiert]

I also followed the advices in thread: https://github.com/PhotoFilmStrip/PFS/issues/19#issuecomment-367027687 - no improvement.

What am I doing wrong?

**Comment by jensgoe** [comment]
probably you are missing gstreamer editing services dependency. package is named gir1.2-ges-1.0 in ubuntu.

**Comment by Mesqualito** [comment]
Thanks to your tip I now have managed to use Photofilmstrip.

Unfortunately, even working with a python3 virtual environment, I am not able to manage it to use Photofilmstrip not as root. I tried with deinstalling everything, deleting `build` and starting "from scratch" with installing all these libraries:
`
$ sudo apt install gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools python3-gst-1.0 gir1.2-ges-1.0
`
`$ sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-good1.0-dev
`
then `wheel` and `wxpython`. Then `python setup.py build` (in Python3.8 virtual environment), `$ sudo python3 setup.py install` and `$ python3 build/scripts-3.8/photofilmstrip`.

Of course I tried every time I used `sudo` a first time without it, but even with `wheel` and `wxpython` I had to use `$ sudo pip3 ...`.

As you can read, I am not really knowing, which part needs which library, why some libraries have to be installed in the OS from distri-packages, some in the OS python3 and only a few can be installed only in an virtual environment with user rights. I am shure there are better ways to get the program to work than mine :-)

I am very thankful for every (short) explanation to be able to read along to get a little bit deeper into the big mystery behind Photofilmstrip.

Thank you a lot for your "cool Ken-Burns-Tool"!
