### ISSUE TITLE
Script to auto generate videos

### ISSUE THREAD

**Issue by yoandyshyno** [PhotoFilmStrip/PFS#8]
I have created a script (**photofilmstrip-auto**) that generate a Video automatically from command line, you must only specify the directory where the photos are.
What it does is to generate a project file with that information, assigning random transitions to the images and then call **photofilmstrip-cli** with the new project file, to render the Video.
I am already using this feature to generate Videos in batch from many directories that contains photos.
If you would like this feature I could send a Pull Request to my forked repo.

For this script in particular I will also work on:

- python3 compatibility.
- use more Clases from photofilmstrip's modules. (E.g. ProjectFile) for compatibility.
- improve further the code for maintainability and simplicity.

**Comment by pepa65** [comment]
I am interested in scripted project generation, but I would like control, like specify the transition, the timing etc.

**Comment by yoandyshyno** [comment]
fair enough @pepa65  I 'll write these as optional parameters with default values accordingly. Thanks.

**Comment by pepa65** [comment]
Is it possible to set the total time as an alternative to setting the time per image?

**Comment by yoandyshyno** [comment]
That could be implemented.

**Comment by jensgoe** [comment]
Hi,
thanks for your effort. I was actually working on a similar issue a while ago ;-)  Regarding Python3 i have already a branch which works. You need wxPython (Phoenix) to run this. Because wxPython is not stable yet i suspended devleopment on this branch.

**Comment by yoandyshyno** [comment]
you're welcome, nice to know you were working on it, cause I realized you are not so open to contributions and I think is a very useful feature. Keep the good work, alles gute.

**Comment by jensgoe** [comment]
Thanks again for your effort. Your script is helpful as an independent script.
